[package]
name = "rsh"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
ctrlc = "3.4.4"
dirs = "5.0.1"
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
whoami = "1.5.1"
